"""
Project Intelligence — deep, structured understanding of each GitHub repo.

Builds and maintains `project_profiles` in SQLite by combining:
  - GitHub API metadata (description, topics, README, CLAUDE.md, CI presence)
  - Cached commit / PR data from gh_commits and gh_pull_requests
  - Docker network topology from network_topology
  - AI tool attribution extracted from commit messages (Co-authored-by signatures)

All query functions are synchronous and read-only (never block on HTTP).
The async refresh functions are safe to call from background tasks.
"""

from __future__ import annotations

import asyncio
import base64
import json
import re
import sqlite3
from datetime import datetime, timezone
from typing import Any

import httpx
from loguru import logger
from pydantic import BaseModel, Field

from .db import _conn, init_db
from .git_history import GITHUB_HEADERS, _init_git_tables


# ── Pydantic models ──────────────────────────────────────────────────────────

class AgentAttribution(BaseModel):
    """Which AI tool(s) created / contributed to a commit."""
    agent_tool: str = "human"          # 'claude-code' | 'cursor' | 'human' | 'copilot' | 'aider' | 'mixed'
    claude_model: str = ""             # e.g. 'Claude Opus 4.6', 'Claude Sonnet 4.5'
    cursor_used: bool = False
    coderabbit_reviewed: bool = False
    other_agents: list[str] = Field(default_factory=list)


class ProjectProfile(BaseModel):
    """Complete intelligence profile for one GitHub repository."""
    repo: str
    owner: str

    # Identity
    display_name: str = ""
    description: str = ""
    purpose: str = ""
    what_it_does_not_do: str = ""
    tech_stack: list[str] = Field(default_factory=list)

    # Infrastructure linkage
    container_name: str = ""
    docker_networks: list[str] = Field(default_factory=list)
    connects_to: list[str] = Field(default_factory=list)
    public_url: str = ""

    # AI tool attribution
    primary_agent: str = ""            # 'claude-code' | 'cursor' | 'human' | 'mixed'
    claude_model: str = ""
    cursor_used: bool = False
    coderabbit_used: bool = False
    other_agents: list[str] = Field(default_factory=list)

    # Development health
    open_issues: int = 0
    total_commits: int = 0
    total_prs: int = 0
    fix_commit_ratio: float = 0.0
    avg_pr_days: float = 0.0
    last_active: str = ""

    # Content extracted from README/CLAUDE.md
    readme_summary: str = ""
    claude_md_exists: bool = False
    readme_exists: bool = False

    # Status flags
    is_active: bool = True
    is_fork: bool = False
    has_docker: bool = False
    has_tests: bool = False
    has_ci: bool = False

    # Revenue readiness
    payment_provider: str = ""   # 'stripe' | 'polar' | 'none'
    has_pricing_ui: bool = False  # pricing route/component exists in repo
    has_payment_webhook: bool = False  # webhook route for stripe/polar exists

    profiled_at: str = ""


class FixPattern(BaseModel):
    """A single fix/bug event extracted from commits or PRs."""
    repo: str
    owner: str
    date: str
    what_broke: str
    how_fixed: str
    agent: str = "human"
    model: str = ""
    pr_number: int = 0
    days_to_fix: float = 0.0
    commit_sha: str = ""
    source: str = "commit"           # 'commit' | 'pr'


# ── Agent detection regexes ───────────────────────────────────────────────────

# Co-authored-by patterns with model extraction
_CLAUDE_CO_AUTHOR_RE = re.compile(
    r'co-authored-by:\s+claude\s*(?P<model>[^\s<]*[^\s<,])?[^<]*<[^>]*anthropic\.com',
    re.IGNORECASE,
)
# Model name patterns embedded in Co-authored-by lines
_MODEL_NAME_RE = re.compile(
    r'(claude\s+(?:opus|sonnet|haiku)\s+[\d.]+|claude\s+(?:opus|sonnet|haiku))',
    re.IGNORECASE,
)
# Footer generated by Claude Code
_CLAUDE_CODE_FOOTER_RE = re.compile(
    r'(?:generated\s+with\s+\[?claude\s+code\]?|🤖\s+generated\s+with\s+\[?claude\s+code\]?)',
    re.IGNORECASE,
)
# Generic noreply@anthropic.com marker
_ANTHROPIC_EMAIL_RE = re.compile(r'noreply@anthropic\.com', re.IGNORECASE)

# Cursor markers
_CURSOR_RE = re.compile(
    r'(?:co-authored-by:\s+cursor|\.cursor/rules|cursor\s+tracking)',
    re.IGNORECASE,
)
# CodeRabbit markers
_CODERABBIT_RE = re.compile(
    r'(?:co-authored-by:\s+coderabbit|coderabbitai\[bot\])',
    re.IGNORECASE,
)
# GitHub Copilot
_COPILOT_RE = re.compile(r'co-authored-by:\s+github-copilot', re.IGNORECASE)
# Aider
_AIDER_RE = re.compile(r'co-authored-by:\s+aider', re.IGNORECASE)


def detect_agents(message: str) -> AgentAttribution:
    """
    Parse a commit message and return which AI tool(s) authored it.

    Detection precedence:
      1. Co-authored-by: Claude <model> <noreply@anthropic.com>  → claude-code
      2. 'Generated with Claude Code' footer                     → claude-code
      3. noreply@anthropic.com anywhere                          → claude-code
      4. Cursor markers                                          → cursor_used=True
      5. CodeRabbit markers                                      → coderabbit_reviewed=True
      6. Copilot / Aider                                         → other_agents
      7. Anything else                                           → human

    If both cursor and claude are detected → agent_tool='mixed'.
    """
    lower = message.lower()
    other_agents: list[str] = []
    cursor_used = False
    coderabbit_reviewed = False
    claude_detected = False
    claude_model = ""

    # ── Claude detection ────────────────────────────────────────────────────
    # Try the full Co-authored-by line first — it may carry the model name
    co_match = _CLAUDE_CO_AUTHOR_RE.search(message)
    if co_match or _ANTHROPIC_EMAIL_RE.search(message) or _CLAUDE_CODE_FOOTER_RE.search(message):
        claude_detected = True
        # Extract model name from the full message
        model_match = _MODEL_NAME_RE.search(message)
        if model_match:
            # Normalise capitalisation: "claude sonnet 4.6" → "Claude Sonnet 4.6"
            raw = model_match.group(0).strip()
            parts = raw.split()
            claude_model = " ".join(p.capitalize() if i < 2 else p for i, p in enumerate(parts))
        else:
            # Try to pull from the co-author token
            if co_match:
                token = (co_match.group("model") or "").strip()
                if token:
                    claude_model = token.replace("-", " ").title()

    # ── Cursor detection ─────────────────────────────────────────────────────
    if _CURSOR_RE.search(message):
        cursor_used = True

    # ── CodeRabbit detection ─────────────────────────────────────────────────
    if _CODERABBIT_RE.search(message):
        coderabbit_reviewed = True

    # ── Other tools ───────────────────────────────────────────────────────────
    if _COPILOT_RE.search(message):
        other_agents.append("copilot")
    if _AIDER_RE.search(message):
        other_agents.append("aider")

    # ── Resolve primary agent ─────────────────────────────────────────────────
    if claude_detected and cursor_used:
        agent_tool = "mixed"
    elif claude_detected:
        agent_tool = "claude-code"
    elif cursor_used:
        agent_tool = "cursor"
    elif "copilot" in other_agents:
        agent_tool = "copilot"
    elif "aider" in other_agents:
        agent_tool = "aider"
    else:
        agent_tool = "human"

    return AgentAttribution(
        agent_tool=agent_tool,
        claude_model=claude_model,
        cursor_used=cursor_used,
        coderabbit_reviewed=coderabbit_reviewed,
        other_agents=other_agents,
    )


# ── DB schema ─────────────────────────────────────────────────────────────────

def _init_intel_tables() -> None:
    """Create / migrate project_profiles and add agent columns to gh_commits."""
    _init_git_tables()
    with _conn() as conn:
        conn.executescript("""
        CREATE TABLE IF NOT EXISTS project_profiles (
            id                   INTEGER PRIMARY KEY AUTOINCREMENT,
            repo                 TEXT NOT NULL,
            owner                TEXT NOT NULL,
            -- Identity
            display_name         TEXT DEFAULT '',
            description          TEXT DEFAULT '',
            purpose              TEXT DEFAULT '',
            what_it_does_not_do  TEXT DEFAULT '',
            tech_stack           TEXT DEFAULT '[]',
            -- Infrastructure linkage
            container_name       TEXT DEFAULT '',
            docker_networks      TEXT DEFAULT '[]',
            connects_to          TEXT DEFAULT '[]',
            public_url           TEXT DEFAULT '',
            -- AI tool attribution
            primary_agent        TEXT DEFAULT '',
            claude_model         TEXT DEFAULT '',
            cursor_used          INTEGER DEFAULT 0,
            coderabbit_used      INTEGER DEFAULT 0,
            other_agents         TEXT DEFAULT '[]',
            -- Development health
            open_issues          INTEGER DEFAULT 0,
            total_commits        INTEGER DEFAULT 0,
            total_prs            INTEGER DEFAULT 0,
            fix_commit_ratio     REAL DEFAULT 0,
            avg_pr_days          REAL DEFAULT 0,
            last_active          TEXT DEFAULT '',
            -- Content extracted from README/CLAUDE.md
            readme_summary       TEXT DEFAULT '',
            claude_md_exists     INTEGER DEFAULT 0,
            readme_exists        INTEGER DEFAULT 0,
            -- Status flags
            is_active            INTEGER DEFAULT 1,
            is_fork              INTEGER DEFAULT 0,
            has_docker           INTEGER DEFAULT 0,
            has_tests            INTEGER DEFAULT 0,
            has_ci               INTEGER DEFAULT 0,
            -- Revenue readiness
            payment_provider     TEXT DEFAULT '',
            has_pricing_ui       INTEGER DEFAULT 0,
            has_payment_webhook  INTEGER DEFAULT 0,
            profiled_at          TEXT NOT NULL,
            UNIQUE(repo, owner)
        );

        CREATE INDEX IF NOT EXISTS idx_profiles_owner  ON project_profiles(owner);
        CREATE INDEX IF NOT EXISTS idx_profiles_active ON project_profiles(is_active);
        CREATE INDEX IF NOT EXISTS idx_profiles_agent  ON project_profiles(primary_agent);
        """)

        # Idempotent column additions for gh_commits (agent columns)
        for col, defn in [
            ("claude_model", "TEXT DEFAULT ''"),
            ("agent_tool",   "TEXT DEFAULT ''"),
        ]:
            try:
                conn.execute(f"ALTER TABLE gh_commits ADD COLUMN {col} {defn}")
            except sqlite3.OperationalError:
                pass  # already exists

        # Idempotent column additions for project_profiles (revenue readiness)
        for col, defn in [
            ("payment_provider",    "TEXT DEFAULT ''"),
            ("has_pricing_ui",      "INTEGER DEFAULT 0"),
            ("has_payment_webhook", "INTEGER DEFAULT 0"),
        ]:
            try:
                conn.execute(f"ALTER TABLE project_profiles ADD COLUMN {col} {defn}")
            except sqlite3.OperationalError:
                pass  # already exists


# ── GitHub API helpers ────────────────────────────────────────────────────────

async def _gh_get(
    client: httpx.AsyncClient,
    url: str,
    params: dict | None = None,
) -> Any:
    """GET a GitHub API endpoint. Returns parsed JSON or None on error."""
    try:
        resp = await client.get(url, headers=GITHUB_HEADERS, params=params, timeout=15.0)
        if resp.status_code == 200:
            return resp.json()
        if resp.status_code == 404:
            return None   # file / resource not found — expected
        logger.warning(f"GitHub API {url} → {resp.status_code}")
        return None
    except Exception as exc:
        logger.warning(f"GitHub API error {url}: {exc}")
        return None


async def _fetch_file_content(
    client: httpx.AsyncClient,
    owner: str,
    repo: str,
    path: str,
) -> str | None:
    """Fetch a file from GitHub contents API, base64-decode, return as string or None."""
    data = await _gh_get(client, f"https://api.github.com/repos/{owner}/{repo}/contents/{path}")
    if not data or not isinstance(data, dict):
        return None
    content_b64 = data.get("content", "")
    if not content_b64:
        return None
    try:
        return base64.b64decode(content_b64.replace("\n", "")).decode("utf-8", errors="replace")
    except Exception:
        return None


async def _path_exists(
    client: httpx.AsyncClient,
    owner: str,
    repo: str,
    path: str,
) -> bool:
    """Return True if the path exists in the default branch (200 from contents API)."""
    data = await _gh_get(client, f"https://api.github.com/repos/{owner}/{repo}/contents/{path}")
    return data is not None


# ── README / CLAUDE.md parsing ────────────────────────────────────────────────

_LIMITATION_HEADERS_RE = re.compile(
    r'^#{1,3}\s*(?:limitation|what\s+it\s+does\s+not|not\s+support|out\s+of\s+scope|caveat|known\s+issue)',
    re.IGNORECASE | re.MULTILINE,
)
_PURPOSE_HEADERS_RE = re.compile(
    r'^#{1,3}\s*(?:overview|purpose|what\s+is|about|description|introduction|what\s+it\s+does)',
    re.IGNORECASE | re.MULTILINE,
)


def _extract_readme_sections(readme: str) -> tuple[str, str]:
    """
    Return (purpose, limitations) extracted from README markdown.
    Heuristic: look for recognised section headers; fall back to first 500 chars.
    """
    purpose = ""
    limitations = ""

    purpose_match = _PURPOSE_HEADERS_RE.search(readme)
    if purpose_match:
        start = purpose_match.end()
        next_header = re.search(r'^#', readme[start:], re.MULTILINE)
        chunk = readme[start : start + (next_header.start() if next_header else 600)].strip()
        purpose = chunk[:500]
    else:
        # Strip leading headings; take first 500 non-empty chars
        stripped = re.sub(r'^#.*$', '', readme, flags=re.MULTILINE).strip()
        purpose = stripped[:500]

    limitation_match = _LIMITATION_HEADERS_RE.search(readme)
    if limitation_match:
        start = limitation_match.end()
        next_header = re.search(r'^#', readme[start:], re.MULTILINE)
        chunk = readme[start : start + (next_header.start() if next_header else 600)].strip()
        limitations = chunk[:400]

    return purpose, limitations


def _infer_tech_stack(language: str, readme: str, has_docker: bool) -> list[str]:
    """Build a deduplicated tech-stack list from language + README keywords."""
    stack: list[str] = []
    if language:
        stack.append(language)

    text = readme.lower()
    patterns: list[tuple[str, str]] = [
        ("next.js", "Next.js"), ("nextjs", "Next.js"),
        ("fastapi", "FastAPI"), ("flask", "Flask"), ("django", "Django"),
        ("react", "React"), ("vue", "Vue"), ("svelte", "Svelte"),
        ("tailwind", "Tailwind CSS"), ("prisma", "Prisma"),
        ("postgresql", "PostgreSQL"), ("postgres", "PostgreSQL"),
        ("sqlite", "SQLite"), ("redis", "Redis"), ("mongodb", "MongoDB"),
        ("docker", "Docker"), ("kubernetes", "Kubernetes"),
        ("github actions", "GitHub Actions"), ("playwright", "Playwright"),
        ("pytest", "pytest"), ("jest", "Jest"), ("vitest", "Vitest"),
        ("openai", "OpenAI"), ("anthropic", "Anthropic"), ("langchain", "LangChain"),
        ("pydantic", "Pydantic"), ("sqlalchemy", "SQLAlchemy"),
        ("bun", "Bun"), ("deno", "Deno"), ("node", "Node.js"),
        ("uv", "uv"), ("poetry", "Poetry"),
        ("twilio", "Twilio"), ("vapi", "VAPI"),
    ]
    for keyword, label in patterns:
        if keyword in text and label not in stack:
            stack.append(label)

    if has_docker and "Docker" not in stack:
        stack.append("Docker")

    return stack[:12]  # cap to avoid noise


# ── Network topology cross-reference ─────────────────────────────────────────

def _lookup_topology(owner: str, repo: str) -> tuple[str, list[str], list[str]]:
    """
    Return (container_name, docker_networks, connects_to) from the services registry
    and/or the network_topology table.  Falls back to empty strings/lists if unknown.
    """
    from .services import SERVICES

    # 1. Try the static services registry (most reliable — human-curated)
    full_name = f"{owner}/{repo}"
    for svc in SERVICES:
        if svc.repo and svc.repo.lower() == full_name.lower():
            return svc.container_name, list(svc.docker_networks), list(svc.connects_to)

    # 2. Try the network_topology table (runtime data from Docker)
    try:
        with _conn() as conn:
            row = conn.execute(
                """SELECT container_name, network_name, connects_to
                   FROM network_topology
                   WHERE service_name LIKE ? OR container_name LIKE ?
                   LIMIT 1""",
                (f"%{repo}%", f"%{repo}%"),
            ).fetchone()
        if row:
            cname = row["container_name"]
            networks_raw: list[str] = []
            connects_raw: list[str] = []
            # Gather all networks for this container
            all_rows = conn.execute(
                "SELECT network_name, connects_to FROM network_topology WHERE container_name=?",
                (cname,),
            ).fetchall()
            for r in all_rows:
                networks_raw.append(r["network_name"])
                try:
                    connects_raw.extend(json.loads(r["connects_to"] or "[]"))
                except Exception:
                    pass
            return cname, list(set(networks_raw)), list(set(connects_raw))
    except Exception:
        pass

    return "", [], []


def _lookup_public_url(owner: str, repo: str, container_name: str) -> str:
    """Return the public HTTPS URL for a repo/container from the services registry."""
    from .services import SERVICES
    full_name = f"{owner}/{repo}"
    for svc in SERVICES:
        if svc.repo and svc.repo.lower() == full_name.lower():
            return svc.url
        if container_name and svc.container_name == container_name:
            return svc.url
    return ""


# ── Commit statistics helpers ─────────────────────────────────────────────────

def _commit_stats_for_repo(owner: str, repo: str) -> dict:
    """
    Read gh_commits and gh_pull_requests from SQLite.
    Returns enriched stats dict including agent attribution.
    """
    with _conn() as conn:
        # Total commits
        total = conn.execute(
            "SELECT COUNT(*) FROM gh_commits WHERE repo=? AND owner=?",
            (repo, owner),
        ).fetchone()[0]

        # Last active date
        last = conn.execute(
            "SELECT MAX(author_date) FROM gh_commits WHERE repo=? AND owner=?",
            (repo, owner),
        ).fetchone()[0]

        # Fix commit ratio (commits whose type is 'fix')
        fix_count = conn.execute(
            "SELECT COUNT(*) FROM gh_commits WHERE repo=? AND owner=? AND commit_type='fix'",
            (repo, owner),
        ).fetchone()[0]

        # Agent breakdown across all commits
        messages = conn.execute(
            "SELECT message FROM gh_commits WHERE repo=? AND owner=?",
            (repo, owner),
        ).fetchall()

        # PR stats
        total_prs = conn.execute(
            "SELECT COUNT(*) FROM gh_pull_requests WHERE repo=? AND owner=?",
            (repo, owner),
        ).fetchone()[0]

        avg_pr_days_row = conn.execute(
            """SELECT AVG(julianday(merged_at) - julianday(created_at))
               FROM gh_pull_requests
               WHERE repo=? AND owner=? AND merged_at IS NOT NULL AND created_at IS NOT NULL""",
            (repo, owner),
        ).fetchone()[0]

    # Tally agent attributions across all commits
    claude_count = 0
    cursor_count = 0
    coderabbit_count = 0
    other_set: set[str] = set()
    claude_models: dict[str, int] = {}

    for row in messages:
        msg = row[0] or ""
        attr = detect_agents(msg)
        if attr.agent_tool in ("claude-code", "mixed"):
            claude_count += 1
            if attr.claude_model:
                claude_models[attr.claude_model] = claude_models.get(attr.claude_model, 0) + 1
        if attr.cursor_used:
            cursor_count += 1
        if attr.coderabbit_reviewed:
            coderabbit_count += 1
        for ag in attr.other_agents:
            other_set.add(ag)

    # Primary agent = most frequent
    if claude_count >= cursor_count and claude_count > 0:
        primary_agent = "claude-code" if cursor_count == 0 else "mixed"
    elif cursor_count > 0:
        primary_agent = "cursor"
    elif other_set:
        primary_agent = next(iter(other_set))
    else:
        primary_agent = "human"

    # Most common Claude model
    top_model = max(claude_models, key=lambda k: claude_models[k]) if claude_models else ""

    return {
        "total_commits": total,
        "last_active": last or "",
        "fix_commit_ratio": round(fix_count / total, 3) if total else 0.0,
        "total_prs": total_prs,
        "avg_pr_days": round(avg_pr_days_row or 0.0, 2),
        "primary_agent": primary_agent,
        "claude_model": top_model,
        "cursor_used": cursor_count > 0,
        "coderabbit_used": coderabbit_count > 0,
        "other_agents": sorted(other_set),
    }


# ── Async repo profiler ───────────────────────────────────────────────────────

async def profile_repo(
    client: httpx.AsyncClient,
    owner: str,
    repo: str,
) -> dict:
    """
    Build a complete profile dict for one repo.

    Combines:
      - GitHub API: repo metadata, README, CLAUDE.md, CI, Dockerfile
      - SQLite cache: commit stats, PR stats, agent attribution
      - Services registry + network_topology: container / URL linkage

    Never raises — returns a partial profile on any failure.
    """
    ts = datetime.now(timezone.utc).isoformat()

    # ── 1. Repo metadata ──────────────────────────────────────────────────────
    meta = await _gh_get(client, f"https://api.github.com/repos/{owner}/{repo}")
    if not meta:
        meta = {}

    description = meta.get("description") or ""
    language = meta.get("language") or ""
    open_issues = meta.get("open_issues_count") or 0
    is_fork = bool(meta.get("fork", False))
    topics: list[str] = meta.get("topics") or []

    # ── 2. File content fetches (parallel) ───────────────────────────────────
    readme_task      = asyncio.create_task(_fetch_file_content(client, owner, repo, "README.md"))
    claude_md_task   = asyncio.create_task(_fetch_file_content(client, owner, repo, "CLAUDE.md"))
    pkg_json_task    = asyncio.create_task(_fetch_file_content(client, owner, repo, "package.json"))
    dockerfile_task  = asyncio.create_task(_path_exists(client, owner, repo, "Dockerfile"))
    ci_task          = asyncio.create_task(_path_exists(client, owner, repo, ".github/workflows"))

    # Test detection: look for common test file patterns
    test_tasks = asyncio.gather(
        _path_exists(client, owner, repo, "tests"),
        _path_exists(client, owner, repo, "test"),
        _path_exists(client, owner, repo, "__tests__"),
        _path_exists(client, owner, repo, "spec"),
        return_exceptions=True,
    )

    # Revenue readiness: pricing UI and webhook routes
    payment_tasks = asyncio.gather(
        _path_exists(client, owner, repo, "app/api/webhooks/stripe"),
        _path_exists(client, owner, repo, "app/api/webhooks/polar"),
        _path_exists(client, owner, repo, "app/api/stripe/webhook"),
        _path_exists(client, owner, repo, "src/app/api/webhooks/polar"),
        _path_exists(client, owner, repo, "src/app/api/webhooks/stripe"),
        _path_exists(client, owner, repo, "components/pricing"),
        _path_exists(client, owner, repo, "app/(marketing)/pricing"),
        _path_exists(client, owner, repo, "app/pricing"),
        return_exceptions=True,
    )

    readme_raw, claude_md_raw, pkg_json_raw, has_docker, has_ci, test_results, payment_results = await asyncio.gather(
        readme_task, claude_md_task, pkg_json_task, dockerfile_task, ci_task, test_tasks, payment_tasks,
    )

    readme_exists = readme_raw is not None
    claude_md_exists = claude_md_raw is not None
    has_tests = any(bool(r) for r in (test_results if isinstance(test_results, tuple | list) else []))

    # Revenue readiness detection
    payment_flags = payment_results if isinstance(payment_results, (tuple, list)) else []
    # First 5 results = webhook routes, last 3 = pricing UI paths
    has_payment_webhook = any(bool(r) for r in payment_flags[:5])
    has_pricing_ui = any(bool(r) for r in payment_flags[5:])

    payment_provider = "none"
    if pkg_json_raw:
        try:
            pkg = json.loads(pkg_json_raw)
            deps = {**pkg.get("dependencies", {}), **pkg.get("devDependencies", {})}
            if "stripe" in deps or "@stripe/stripe-js" in deps or "stripe-event-types" in deps:
                payment_provider = "stripe"
            elif "@polar-sh/sdk" in deps or "polar" in deps:
                payment_provider = "polar"
        except Exception:
            pass

    readme_text = readme_raw or ""
    purpose, what_it_does_not_do = _extract_readme_sections(readme_text)
    readme_summary = readme_text[:500]

    # ── 3. Tech stack inference ───────────────────────────────────────────────
    tech_stack = _infer_tech_stack(language, readme_text, bool(has_docker))
    if topics:
        for t in topics:
            normalised = t.replace("-", " ").title()
            if normalised not in tech_stack:
                tech_stack.append(normalised)
    tech_stack = tech_stack[:15]

    # ── 4. Infrastructure linkage ─────────────────────────────────────────────
    container_name, docker_networks, connects_to = _lookup_topology(owner, repo)
    public_url = _lookup_public_url(owner, repo, container_name)

    # ── 5. Commit / PR stats + agent attribution ──────────────────────────────
    try:
        stats = _commit_stats_for_repo(owner, repo)
    except Exception as exc:
        logger.warning(f"Commit stats failed for {owner}/{repo}: {exc}")
        stats = {
            "total_commits": 0, "last_active": "", "fix_commit_ratio": 0.0,
            "total_prs": 0, "avg_pr_days": 0.0, "primary_agent": "human",
            "claude_model": "", "cursor_used": False,
            "coderabbit_used": False, "other_agents": [],
        }

    # ── 6. Activity flag (no commits in 90 days → inactive) ──────────────────
    is_active = True
    last_active = stats.get("last_active") or meta.get("pushed_at") or ""
    if last_active:
        try:
            # Normalise — SQLite dates may or may not have timezone info
            la_str = last_active.rstrip("Z") + "+00:00" if last_active.endswith("Z") else last_active
            last_dt = datetime.fromisoformat(la_str)
            now_dt = datetime.now(timezone.utc)
            if last_dt.tzinfo is None:
                last_dt = last_dt.replace(tzinfo=timezone.utc)
            is_active = (now_dt - last_dt).days < 90
        except Exception:
            pass

    # ── 7. Assemble profile dict ──────────────────────────────────────────────
    return {
        "repo": repo,
        "owner": owner,
        "display_name": repo.replace("-", " ").replace("_", " ").title(),
        "description": description,
        "purpose": purpose,
        "what_it_does_not_do": what_it_does_not_do,
        "tech_stack": json.dumps(tech_stack),
        "container_name": container_name,
        "docker_networks": json.dumps(docker_networks),
        "connects_to": json.dumps(connects_to),
        "public_url": public_url,
        "primary_agent": stats["primary_agent"],
        "claude_model": stats["claude_model"],
        "cursor_used": int(stats["cursor_used"]),
        "coderabbit_used": int(stats["coderabbit_used"]),
        "other_agents": json.dumps(stats["other_agents"]),
        "open_issues": open_issues,
        "total_commits": stats["total_commits"],
        "total_prs": stats["total_prs"],
        "fix_commit_ratio": stats["fix_commit_ratio"],
        "avg_pr_days": stats["avg_pr_days"],
        "last_active": last_active,
        "readme_summary": readme_summary,
        "claude_md_exists": int(claude_md_exists),
        "readme_exists": int(readme_exists),
        "is_active": int(is_active),
        "is_fork": int(is_fork),
        "has_docker": int(bool(has_docker)),
        "has_tests": int(bool(has_tests)),
        "has_ci": int(bool(has_ci)),
        "payment_provider": payment_provider,
        "has_pricing_ui": int(has_pricing_ui),
        "has_payment_webhook": int(has_payment_webhook),
        "profiled_at": ts,
    }


def _upsert_profile(profile: dict) -> None:
    """Write a profile dict into project_profiles (INSERT OR REPLACE)."""
    with _conn() as conn:
        conn.execute(
            """INSERT INTO project_profiles
               (repo, owner, display_name, description, purpose, what_it_does_not_do,
                tech_stack, container_name, docker_networks, connects_to, public_url,
                primary_agent, claude_model, cursor_used, coderabbit_used, other_agents,
                open_issues, total_commits, total_prs, fix_commit_ratio, avg_pr_days,
                last_active, readme_summary, claude_md_exists, readme_exists,
                is_active, is_fork, has_docker, has_tests, has_ci,
                payment_provider, has_pricing_ui, has_payment_webhook, profiled_at)
               VALUES
               (:repo,:owner,:display_name,:description,:purpose,:what_it_does_not_do,
                :tech_stack,:container_name,:docker_networks,:connects_to,:public_url,
                :primary_agent,:claude_model,:cursor_used,:coderabbit_used,:other_agents,
                :open_issues,:total_commits,:total_prs,:fix_commit_ratio,:avg_pr_days,
                :last_active,:readme_summary,:claude_md_exists,:readme_exists,
                :is_active,:is_fork,:has_docker,:has_tests,:has_ci,
                :payment_provider,:has_pricing_ui,:has_payment_webhook,:profiled_at)
               ON CONFLICT(repo, owner) DO UPDATE SET
                 display_name=excluded.display_name,
                 description=excluded.description,
                 purpose=excluded.purpose,
                 what_it_does_not_do=excluded.what_it_does_not_do,
                 tech_stack=excluded.tech_stack,
                 container_name=excluded.container_name,
                 docker_networks=excluded.docker_networks,
                 connects_to=excluded.connects_to,
                 public_url=excluded.public_url,
                 primary_agent=excluded.primary_agent,
                 claude_model=excluded.claude_model,
                 cursor_used=excluded.cursor_used,
                 coderabbit_used=excluded.coderabbit_used,
                 other_agents=excluded.other_agents,
                 open_issues=excluded.open_issues,
                 total_commits=excluded.total_commits,
                 total_prs=excluded.total_prs,
                 fix_commit_ratio=excluded.fix_commit_ratio,
                 avg_pr_days=excluded.avg_pr_days,
                 last_active=excluded.last_active,
                 readme_summary=excluded.readme_summary,
                 claude_md_exists=excluded.claude_md_exists,
                 readme_exists=excluded.readme_exists,
                 is_active=excluded.is_active,
                 is_fork=excluded.is_fork,
                 has_docker=excluded.has_docker,
                 has_tests=excluded.has_tests,
                 has_ci=excluded.has_ci,
                 payment_provider=excluded.payment_provider,
                 has_pricing_ui=excluded.has_pricing_ui,
                 has_payment_webhook=excluded.has_payment_webhook,
                 profiled_at=excluded.profiled_at""",
            profile,
        )


# ── Bulk refresh ──────────────────────────────────────────────────────────────

_profile_lock = asyncio.Lock()
_profile_running = False


async def refresh_all_profiles(force: bool = False) -> dict:
    """
    Profile every repo in gh_repos and upsert into project_profiles.

    Uses semaphore(5) so we don't hammer the GitHub API.
    Safe to call from background tasks — acquires a module-level lock.

    Returns:
        {
            "status": "ok",
            "repos_scanned": N,
            "profiles_saved": N,
            "errors": N,
        }
    """
    global _profile_running
    if _profile_running and not force:
        return {"status": "already_running"}

    async with _profile_lock:
        _profile_running = True
        try:
            return await _do_refresh_profiles(force)
        finally:
            _profile_running = False


async def _do_refresh_profiles(force: bool = False) -> dict:
    _init_intel_tables()

    with _conn() as conn:
        repo_rows = conn.execute(
            "SELECT full_name, owner, name FROM gh_repos ORDER BY pushed_at DESC"
        ).fetchall()

    if not repo_rows:
        logger.warning("No repos in gh_repos — run git_history.refresh_all() first")
        return {"status": "ok", "repos_scanned": 0, "profiles_saved": 0, "errors": 0}

    sem = asyncio.Semaphore(5)
    errors = 0
    saved = 0

    async def _do_one(client: httpx.AsyncClient, owner: str, repo: str) -> bool:
        nonlocal errors, saved
        async with sem:
            try:
                profile = await profile_repo(client, owner, repo)
                _upsert_profile(profile)
                saved += 1
                logger.debug(f"  Profiled {owner}/{repo} — agent={profile['primary_agent']}")
                return True
            except Exception as exc:
                logger.warning(f"Profile failed for {owner}/{repo}: {exc}")
                errors += 1
                return False

    async with httpx.AsyncClient() as client:
        tasks = [
            _do_one(client, r["owner"], r["name"])
            for r in repo_rows
        ]
        await asyncio.gather(*tasks)

    logger.info(f"Profile refresh done: {saved} saved, {errors} errors, {len(repo_rows)} total")
    return {
        "status": "ok",
        "repos_scanned": len(repo_rows),
        "profiles_saved": saved,
        "errors": errors,
    }


# ── Query functions (synchronous, read-only) ──────────────────────────────────

def _deserialise_profile(row: sqlite3.Row | dict) -> dict:
    """Convert a raw DB row into a clean dict with JSON fields expanded."""
    d = dict(row)
    for field in ("tech_stack", "docker_networks", "connects_to", "other_agents"):
        try:
            d[field] = json.loads(d[field]) if d.get(field) else []
        except Exception:
            d[field] = []
    for field in ("cursor_used", "coderabbit_used", "claude_md_exists",
                  "readme_exists", "is_active", "is_fork",
                  "has_docker", "has_tests", "has_ci",
                  "has_pricing_ui", "has_payment_webhook"):
        if field in d:
            d[field] = bool(d[field])
    return d


def get_project_profile(repo: str, owner: str | None = None) -> dict | None:
    """
    Return the cached profile for a single repo, or None if not yet profiled.

    Args:
        repo:  Repository name (e.g. 'wes') OR full name (e.g. 'Mark0025/wes').
        owner: GitHub owner/org — inferred from `repo` if it contains '/'.
    """
    _init_intel_tables()

    # Allow 'owner/repo' as a single arg
    if "/" in repo and owner is None:
        owner, repo = repo.split("/", 1)

    with _conn() as conn:
        if owner:
            row = conn.execute(
                "SELECT * FROM project_profiles WHERE repo=? AND owner=?",
                (repo, owner),
            ).fetchone()
        else:
            row = conn.execute(
                "SELECT * FROM project_profiles WHERE repo=? ORDER BY profiled_at DESC LIMIT 1",
                (repo,),
            ).fetchone()

    return _deserialise_profile(row) if row else None


def get_all_profiles(active_only: bool = True) -> list[dict]:
    """
    Return all cached profiles.

    Args:
        active_only: When True (default) skip repos with no commits in 90 days.
    """
    _init_intel_tables()
    query = "SELECT * FROM project_profiles"
    if active_only:
        query += " WHERE is_active=1"
    query += " ORDER BY total_commits DESC"
    with _conn() as conn:
        rows = conn.execute(query).fetchall()
    return [_deserialise_profile(r) for r in rows]


def get_agent_stats() -> dict:
    """
    Aggregate breakdown of AI tool usage across all commits.
    Reads from enriched gh_commits (always available) + project_profiles (when profiled).
    """
    _init_intel_tables()
    with _conn() as conn:
        # Primary source: enriched commits (always populated after enrich_commits_with_agents)
        commit_rows = conn.execute("""
            SELECT agent_tool, claude_model, COUNT(*) as cnt
            FROM gh_commits
            WHERE agent_tool IS NOT NULL AND agent_tool != ''
            GROUP BY agent_tool, claude_model
            ORDER BY cnt DESC
        """).fetchall()

        total_commits = conn.execute("SELECT COUNT(*) FROM gh_commits").fetchone()[0]
        total_repos = conn.execute("SELECT COUNT(DISTINCT repo) FROM gh_commits").fetchone()[0]

        # Per-repo agent breakdown
        repo_agents = conn.execute("""
            SELECT repo, owner,
                   SUM(CASE WHEN agent_tool IN ('claude-code','mixed') THEN 1 ELSE 0 END) as claude_cnt,
                   SUM(CASE WHEN agent_tool = 'cursor' THEN 1 ELSE 0 END) as cursor_cnt,
                   SUM(CASE WHEN agent_tool = 'human' THEN 1 ELSE 0 END) as human_cnt,
                   COUNT(*) as total
            FROM gh_commits
            GROUP BY repo, owner
            ORDER BY total DESC
            LIMIT 20
        """).fetchall()

    by_agent: dict[str, int] = {}
    by_model: list[dict] = []
    for r in commit_rows:
        agent = r["agent_tool"] or "human"
        by_agent[agent] = by_agent.get(agent, 0) + r["cnt"]
        if r["claude_model"]:
            by_model.append({"claude_model": r["claude_model"], "cnt": r["cnt"]})

    claude_count = sum(v for k, v in by_agent.items() if k in ("claude-code", "mixed"))
    cursor_count = by_agent.get("cursor", 0) + sum(v for k, v in by_agent.items() if k == "mixed")
    human_count  = by_agent.get("human", 0)
    top_agent    = max(by_agent, key=lambda k: by_agent[k]) if by_agent else "human"

    return {
        "total_commits": total_commits,
        "total_repos": total_repos,
        "by_agent": by_agent,
        "by_model": by_model,
        "claude_pct": round(100 * claude_count / total_commits, 1) if total_commits else 0,
        "cursor_pct": round(100 * cursor_count / total_commits, 1) if total_commits else 0,
        "human_pct":  round(100 * human_count  / total_commits, 1) if total_commits else 0,
        "top_agent": top_agent,
        "repo_breakdown": [dict(r) for r in repo_agents],
    }


def search_profiles(query: str) -> list[dict]:
    """
    Full-text search across purpose, description, and readme_summary.

    Args:
        query: Freeform search string. Searched as substring (case-insensitive).

    Returns:
        Matching profiles ordered by total_commits DESC.
    """
    _init_intel_tables()
    pattern = f"%{query}%"
    with _conn() as conn:
        rows = conn.execute(
            """SELECT * FROM project_profiles
               WHERE purpose LIKE ?
                  OR description LIKE ?
                  OR readme_summary LIKE ?
                  OR repo LIKE ?
                  OR display_name LIKE ?
               ORDER BY total_commits DESC""",
            (pattern, pattern, pattern, pattern, pattern),
        ).fetchall()
    return [_deserialise_profile(r) for r in rows]


# ── Fix / problem pattern extractor ──────────────────────────────────────────

_FIX_COMMIT_RE = re.compile(
    r'^(?:fix|bug|resolve|patch|hotfix|repair|revert)[\s(:!]',
    re.IGNORECASE,
)
_FIX_PR_TITLE_RE = re.compile(
    r'\b(?:fix(?:ed|es)?|bug|broken|resolve[sd]?|error|crash|fail(?:ed|s)?|'
    r'regression|hotfix|patch|revert)\b',
    re.IGNORECASE,
)
_HOW_FIXED_RE = re.compile(
    r'(?:by|via|using|with|through|replaced?|updated?|added?|removed?|increased?|'
    r'decreased?|changed?|switched?|migrated?)\s+.{5,100}',
    re.IGNORECASE,
)


def _extract_how_fixed(message: str) -> str:
    """
    Try to pull the 'how' out of a commit message body.
    Falls back to the first non-empty body line.
    """
    lines = message.split("\n")
    body_lines = [l.strip() for l in lines[1:] if l.strip() and not l.startswith("Co-")]
    for line in body_lines:
        m = _HOW_FIXED_RE.search(line)
        if m:
            return line[:200]
    return body_lines[0][:200] if body_lines else ""


def extract_fix_patterns(repo: str | None = None) -> list[dict]:
    """
    Query cached commits and PRs to find fix/bug events.

    Args:
        repo: Optional repo name filter. None = all repos.

    Returns list of FixPattern dicts with:
        repo, owner, date, what_broke, how_fixed, agent, model,
        pr_number, days_to_fix, commit_sha, source
    """
    _init_intel_tables()
    results: list[dict] = []

    # ── Part A: fix: commits ──────────────────────────────────────────────────
    commit_query = """
        SELECT sha, repo, owner, message, author_date, pr_number, additions, deletions
        FROM gh_commits
        WHERE commit_type = 'fix'
    """
    params: list[Any] = []
    if repo:
        commit_query += " AND repo=?"
        params.append(repo)
    commit_query += " ORDER BY author_date DESC LIMIT 2000"

    with _conn() as conn:
        commit_rows = conn.execute(commit_query, params).fetchall()

    for row in commit_rows:
        msg = row["message"] or ""
        subject = msg.split("\n")[0].strip()
        attr = detect_agents(msg)

        # days_to_fix: try to match against a PR
        days_to_fix = 0.0
        pr_num = row["pr_number"] or 0

        if pr_num:
            with _conn() as conn:
                pr_row = conn.execute(
                    """SELECT julianday(merged_at) - julianday(created_at) as d
                       FROM gh_pull_requests
                       WHERE repo=? AND owner=? AND number=?""",
                    (row["repo"], row["owner"], pr_num),
                ).fetchone()
            if pr_row and pr_row["d"] is not None:
                days_to_fix = round(float(pr_row["d"]), 2)

        results.append(FixPattern(
            repo=row["repo"],
            owner=row["owner"],
            date=row["author_date"][:10] if row["author_date"] else "",
            what_broke=subject,
            how_fixed=_extract_how_fixed(msg),
            agent=attr.agent_tool,
            model=attr.claude_model,
            pr_number=pr_num,
            days_to_fix=days_to_fix,
            commit_sha=row["sha"][:7],
            source="commit",
        ).model_dump())

    # ── Part B: fix PRs ───────────────────────────────────────────────────────
    pr_query = """
        SELECT number, repo, owner, title, body, merged_at, created_at,
               julianday(merged_at) - julianday(created_at) as days_open
        FROM gh_pull_requests
        WHERE merged_at IS NOT NULL
          AND (
            title LIKE '%fix%' OR title LIKE '%bug%' OR title LIKE '%broken%'
            OR title LIKE '%resolve%' OR title LIKE '%error%' OR title LIKE '%revert%'
            OR title LIKE '%crash%' OR title LIKE '%fail%' OR title LIKE '%hotfix%'
          )
    """
    pr_params: list[Any] = []
    if repo:
        pr_query += " AND repo=?"
        pr_params.append(repo)
    pr_query += " ORDER BY merged_at DESC LIMIT 500"

    with _conn() as conn:
        pr_rows = conn.execute(pr_query, pr_params).fetchall()

    for row in pr_rows:
        body = row["body"] or ""
        attr = detect_agents(body)
        results.append(FixPattern(
            repo=row["repo"],
            owner=row["owner"],
            date=(row["merged_at"] or "")[:10],
            what_broke=row["title"],
            how_fixed=_extract_how_fixed(body),
            agent=attr.agent_tool,
            model=attr.claude_model,
            pr_number=row["number"],
            days_to_fix=round(float(row["days_open"] or 0), 2),
            commit_sha="",
            source="pr",
        ).model_dump())

    # Deduplicate by (repo, pr_number) — prefer commit source
    seen: set[tuple[str, int]] = set()
    deduped: list[dict] = []
    for item in results:
        key = (item["repo"], item["pr_number"])
        if item["pr_number"] and key in seen:
            continue
        if item["pr_number"]:
            seen.add(key)
        deduped.append(item)

    # Sort: most recent first
    deduped.sort(key=lambda x: x.get("date", ""), reverse=True)
    return deduped


# Keep as alias for backwards-compat
get_fix_patterns = extract_fix_patterns


# ── Enrich gh_commits with agent columns ─────────────────────────────────────

def enrich_commits_with_agents() -> int:
    """
    Backfill agent_tool and claude_model columns on gh_commits rows
    that haven't been classified yet.

    Returns number of rows updated.
    """
    _init_intel_tables()
    with _conn() as conn:
        rows = conn.execute(
            "SELECT sha, repo, message FROM gh_commits WHERE agent_tool = '' OR agent_tool IS NULL"
        ).fetchall()

    if not rows:
        return 0

    updates: list[tuple[str, str, str, str]] = []
    for row in rows:
        attr = detect_agents(row["message"] or "")
        updates.append((attr.agent_tool, attr.claude_model, row["sha"], row["repo"]))

    with _conn() as conn:
        conn.executemany(
            "UPDATE gh_commits SET agent_tool=?, claude_model=? WHERE sha=? AND repo=?",
            updates,
        )
    logger.debug(f"Enriched {len(updates)} commits with agent attribution")
    return len(updates)
