"""All known homelab endpoints with descriptions and metadata."""

from pydantic import BaseModel


class Service(BaseModel):
    name: str
    url: str
    category: str
    description: str
    what_it_does: str
    repo: str = ""
    has_api: bool = False
    has_docs_path: str = ""
    health_path: str = ""
    container_name: str = ""
    docker_networks: list[str] = []
    connects_to: list[str] = []

    model_config = {"frozen": True}


SERVICES: list[Service] = [
    # ─── TERRY AGENT ──────────────────────────────────────────────────────────
    Service(
        name="Terry Management",
        url="https://terry.markcarpenter1.com",
        category="terry",
        description="Main control panel for Terry autonomous AI agent",
        what_it_does="Give Terry instructions, see what he's working on, pause/resume him, manage task queue.",
        repo="Mark0025/00Myhomelab",
        container_name="terry-management",
        docker_networks=["nginx-network"],
        connects_to=["terry-backend", "terry-memory", "terry-performance-api"],
    ),
    Service(
        name="Terry Viewer",
        url="https://terry-viewer.markcarpenter1.com",
        category="terry",
        description="Read-only history log of everything Terry has done",
        what_it_does="Browse every task Terry completed, every file changed, every result — like a work journal.",
        repo="Mark0025/00Myhomelab",
        container_name="terry-viewer-next",
        docker_networks=["nginx-network"],
        connects_to=["terry-backend"],
    ),
    Service(
        name="Terry Backend API",
        url="https://terry-backend.markcarpenter1.com",
        category="terry",
        description="The engine behind Terry — work queue, quality scoring, blockers",
        what_it_does="FastAPI service handling Terry's work queue, commit quality analysis, blocker tracking, and data feeds to the management dashboard.",
        repo="Mark0025/00Myhomelab",
        has_api=True,
        has_docs_path="/docs",
        health_path="/health",
        container_name="terry-backend",
        docker_networks=["nginx-network"],
        connects_to=["terry-memory", "terry-performance-api"],
    ),
    Service(
        name="Terry Performance API",
        url="https://terry-performance-api.markcarpenter1.com",
        category="terry",
        description="ROI tracker — calculates dollar value of Terry's work",
        what_it_does="Tracks cycles completed, computes market-equivalent salary ($70k-$117k/yr), grades performance against DevOps benchmarks.",
        repo="Mark0025/00Myhomelab",
        has_api=True,
        has_docs_path="/docs",
        health_path="/health",
        container_name="terry-performance-api",
        docker_networks=["nginx-network"],
        connects_to=["terry-backend"],
    ),
    Service(
        name="Terry Memory",
        url="https://terry-memory.markcarpenter1.com",
        category="terry",
        description="Short-term session memory for Terry",
        what_it_does="Stores Terry's active session context so he picks up exactly where he left off after pause or restart.",
        repo="Mark0025/00Myhomelab",
        has_api=True,
        has_docs_path="/docs",
        health_path="/health",
        container_name="terry-memory",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Terry Conversation",
        url="https://terry-conversation.markcarpenter1.com",
        category="terry",
        description="Chat interface to talk to Terry directly",
        what_it_does="Plain-English chat — ask Terry questions about the codebase or give instructions like a messaging app.",
        repo="Mark0025/00Myhomelab",
        has_api=True,
        has_docs_path="/docs",
        container_name="terry-conversation",
        docker_networks=["nginx-network"],
        connects_to=["terry-backend", "terry-memory"],
    ),
    Service(
        name="PR Reviewer",
        url="https://pr-reviewer.markcarpenter1.com",
        category="terry",
        description="Automatic GitHub PR reviewer triggered by git hooks",
        what_it_does="The moment a PR opens, analyzes risks, race conditions, dependency issues — no human has to read the code.",
        repo="Mark0025/pr-reviewer",
        has_api=True,
        has_docs_path="/docs",
        container_name="terry-review-webhook",
        docker_networks=["nginx-network"],
        connects_to=["terry-backend"],
    ),
    Service(
        name="Terry UI Dev",
        url="https://terry-mgmt.markcarpenter1.com",
        category="terry",
        description="Development version of Terry management UI",
        what_it_does="Staging environment for testing new Terry management features before deploying to production.",
        repo="Mark0025/00Myhomelab",
        container_name="terry-ui-dev",
        docker_networks=["nginx-network"],
        connects_to=["terry-backend"],
    ),

    # ─── TERRY DEPLOY WEBHOOKS ────────────────────────────────────────────────
    Service(
        name="Deploy Terry Backend",
        url="https://deploy-terry-backend.markcarpenter1.com",
        category="deploy",
        description="Webhook that auto-deploys Terry Backend on git push",
        what_it_does="Listens for a GitHub push to the terry-backend repo and automatically pulls and restarts the container — hands-free deployment.",
        container_name="terry-backend-webhook",
        docker_networks=["nginx-network"],
        connects_to=["terry-backend"],
    ),
    Service(
        name="Deploy Terry Management",
        url="https://deploy-terry-mgmt.markcarpenter1.com",
        category="deploy",
        description="Webhook that auto-deploys Terry Management on git push",
        what_it_does="Listens for a GitHub push and automatically redeploys the Terry management dashboard without any manual steps.",
        container_name="terry-management-webhook",
        docker_networks=["nginx-network"],
        connects_to=["terry-management"],
    ),
    Service(
        name="Deploy Terry Viewer",
        url="https://deploy-terry-viewer.markcarpenter1.com",
        category="deploy",
        description="Webhook that auto-deploys Terry Viewer on git push",
        what_it_does="Automatically redeploys the Terry history viewer when code is pushed to its repo.",
        container_name="terry-viewer-next-webhook",
        docker_networks=["nginx-network"],
        connects_to=["terry-viewer-next"],
    ),
    Service(
        name="Deploy Pete DB",
        url="https://deploy-pete-db.markcarpenter1.com",
        category="deploy",
        description="Webhook that auto-deploys Pete DB API on git push",
        what_it_does="Listens for code changes and automatically restarts the Pete database API — no manual SSH required.",
        container_name="pete-db-webhook",
        docker_networks=["nginx-network", "pete-network"],
        connects_to=["pete-db-api"],
    ),
    Service(
        name="Deploy Agent EOS",
        url="https://deploy-agent-eos.markcarpenter1.com",
        category="deploy",
        description="Webhook that auto-deploys Agent EOS on git push",
        what_it_does="Automatically redeploys the EOS agent framework when code changes are pushed.",
        container_name="agent-eos-webhook",
        docker_networks=["nginx-network"],
        connects_to=["agent-eos"],
    ),
    Service(
        name="Deploy NPM Auth",
        url="https://deploy-npm-auth.markcarpenter1.com",
        category="deploy",
        description="Webhook that auto-deploys the NPM auth proxy on git push",
        what_it_does="Automatically redeploys the Nginx Proxy Manager authentication proxy when code changes.",
        container_name="npm-auth-webhook",
        docker_networks=["nginx-network"],
        connects_to=["npm-auth-proxy"],
    ),
    Service(
        name="Deploy Pete Visualizer",
        url="https://deploy-petevisualizer.markcarpenter1.com",
        category="deploy",
        description="Webhook that auto-deploys Pete Visualizer on git push",
        what_it_does="Automatically redeploys the Pete CRM visualization dashboard when code is pushed.",
        container_name="petevisualizer-webhook",
        docker_networks=["nginx-network", "pete-network"],
        connects_to=["petevisualizer"],
    ),
    Service(
        name="Deploy Skip Tracing",
        url="https://deploy-skip-tracing.markcarpenter1.com",
        category="deploy",
        description="Webhook that auto-deploys Skip Tracing service on git push",
        what_it_does="Automatically redeploys the skip tracing lookup service when code changes are pushed to the repo.",
        container_name="skip-tracing-webhook",
        docker_networks=["nginx-network", "pete-network"],
        connects_to=["skip-tracing"],
    ),
    Service(
        name="Deploy Twilio Tools",
        url="https://deploy-twilio-tools.markcarpenter1.com",
        category="deploy",
        description="Webhook that auto-deploys Twilio Tools on git push",
        what_it_does="Automatically redeploys the Twilio tools stack (frontend and backend) when code is pushed.",
        container_name="twilio-tools-webhook",
        docker_networks=["nginx-network"],
        connects_to=["twilio-backend", "twilio-frontend"],
    ),
    Service(
        name="Pete Intercom Webhook",
        url="https://pete-intercom.markcarpenter1.com",
        category="deploy",
        description="Webhook handler for Pete Intercom auto-deployment",
        what_it_does="Listens for push events and automatically redeploys the Pete Intercom email/messaging service.",
        container_name="pete-intercom-webhook",
        docker_networks=["nginx-network"],
        connects_to=["pete-intercom-app"],
    ),

    # ─── PETE — REAL ESTATE CRM ───────────────────────────────────────────────
    Service(
        name="Pete DB API",
        url="https://pete-db-api.markcarpenter1.com",
        category="pete",
        description="Core database API for all Pete real estate data",
        what_it_does="Properties, leads, contacts, deal status — the filing cabinet every Pete service reads from and writes to.",
        has_api=True,
        has_docs_path="/docs",
        health_path="/health",
        container_name="pete-db-api",
        docker_networks=["nginx-network", "pete-network"],
        connects_to=["pete-redis"],
    ),
    Service(
        name="Pete DB UI",
        url="https://pete-db-ui.markcarpenter1.com",
        category="pete",
        description="Web UI to browse and manage the Pete database",
        what_it_does="Spreadsheet-style view of all real estate records — browse, search, manage leads and contacts.",
        container_name="pete-db-ui",
        docker_networks=["nginx-network", "pete-network"],
        connects_to=["pete-db-api"],
    ),
    Service(
        name="Pete FastAPI",
        url="https://pete-fastapi.markcarpenter1.com",
        category="pete",
        description="Main business logic engine for Pete CRM",
        what_it_does="Processes leads, runs calculations, coordinates between services — the backend brain of the Pete stack.",
        has_api=True,
        has_docs_path="/docs",
        health_path="/health",
        container_name="pete-fastapi",
        docker_networks=["nginx-network", "pete-network"],
        connects_to=["pete-db-api", "pete-redis"],
    ),
    Service(
        name="Pete Jamie",
        url="https://pete-jamie.markcarpenter1.com",
        category="pete",
        description="AI voice assistant for incoming phone calls",
        what_it_does="Answers calls with AI, checks Google Calendar, looks up the caller in CRM, responds intelligently using local models + Azure DB.",
        has_api=True,
        has_docs_path="/docs",
        container_name="pete-jamie-app",
        docker_networks=["nginx-network"],
        connects_to=["pete-db-api", "vapi2simple-api"],
    ),
    Service(
        name="Pete Data Cleaner",
        url="https://pete-cleandata.markcarpenter1.com",
        category="pete",
        description="DealMachine export cleaner — messy → Pete-ready",
        what_it_does="Takes messy DealMachine CSV exports and normalizes them to one-row-per-address records ready for Pete CRM import.",
        repo="Mark0025/pete-data-sanitizer",
        container_name="pete-cleandata",
        docker_networks=["nginx-network", "pete-network"],
        connects_to=["pete-db-api"],
    ),
    Service(
        name="Pete Data Cleaner API",
        url="https://pete-datacleaner.markcarpenter1.com",
        category="pete",
        description="API endpoint for Pete data cleaning operations",
        what_it_does="Programmatic data cleaning for DealMachine exports — accepts CSV uploads and returns normalized real estate records.",
        has_api=True,
        has_docs_path="/docs",
        container_name="pete-datacleaner-api",
        docker_networks=["nginx-network"],
        connects_to=["pete-db-api"],
    ),
    Service(
        name="Pete Intercom",
        url="https://pete-intercom.markcarpenter1.com",
        category="pete",
        description="Outbound email/messaging to leads via Intercom",
        what_it_does="Sends follow-up emails and messages automatically when new leads come in or follow-ups are due.",
        container_name="pete-intercom-app",
        docker_networks=["nginx-network"],
        connects_to=["pete-db-api"],
    ),
    Service(
        name="Pete Image Generator",
        url="https://pete-image-generator.markcarpenter1.com",
        category="pete",
        description="AI image generation for marketing materials",
        what_it_does="Generates property photos, thumbnails, and ads using RunPod cloud GPU on the backend.",
        container_name="pete-image-generator",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Pete Dev Tools",
        url="https://pete-dev-tools.markcarpenter1.com",
        category="pete",
        description="Developer debug dashboard for the Pete stack",
        what_it_does="Used when something breaks — inspect internals, check data flow, look under the hood of the CRM.",
        container_name="pete-dev-tools-ui",
        docker_networks=["nginx-network", "pete-network"],
        connects_to=["pete-db-api", "pete-fastapi"],
    ),
    Service(
        name="Pete Visualizer",
        url="https://petevisualizer.markcarpenter1.com",
        category="pete",
        description="Charts for Pete CRM — pipeline, leads, deals",
        what_it_does="Turns raw CRM numbers into visual dashboards: pipeline activity, lead volume, deal progress over time.",
        repo="Mark0025/pete-company-ops-viewer",
        container_name="petevisualizer",
        docker_networks=["nginx-network", "pete-network"],
        connects_to=["pete-db-api"],
    ),
    Service(
        name="Skip Tracing",
        url="https://skip-tracing.markcarpenter1.com",
        category="pete",
        description="Property address → owner contact lookup",
        what_it_does="Give it an address; get back phone, email, and owner details in a 129-column CSV ready for Pete CRM.",
        repo="Mark0025/skip-tracing",
        has_api=True,
        has_docs_path="/docs",
        container_name="skip-tracing",
        docker_networks=["nginx-network", "pete-network"],
        connects_to=["pete-db-api"],
    ),
    Service(
        name="White Glove Dashboard",
        url="https://white-glove.markcarpenter1.com",
        category="pete",
        description="Client onboarding progress tracker",
        what_it_does="Shows every step of the White Glove setup checklist — what's done, what's pending for each new Pete client.",
        repo="Mark0025/white-glove-dashboard",
        container_name="white-glove-dashboard",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="IF3 Scraper",
        url="https://if3scraper.markcarpenter1.com",
        category="pete",
        description="InvestorFuse CRM data extractor",
        what_it_does="Pulls data out of InvestorFuse for migration or analysis. Built specifically for CVA Homes White Glove migration.",
        repo="Mark0025/if3scraper",
        container_name="if3scraper-report",
        docker_networks=["nginx-network", "pete-network"],
        connects_to=["pete-db-api"],
    ),
    Service(
        name="Local Leasing",
        url="https://localleasing.markcarpenter1.com",
        category="pete",
        description="Local leasing property management site",
        what_it_does="Rental property management — lease tracking, tenant info, local listings.",
        container_name="scott-localleasing-frontend",
        docker_networks=["nginx-network"],
        connects_to=["scott-localleasing-backend"],
    ),
    Service(
        name="Local Leasing API",
        url="https://api.localleasing.markcarpenter1.com",
        category="pete",
        description="Backend API for the Local Leasing property management platform",
        what_it_does="Handles the data layer for leasing — stores lease agreements, tenant records, and property listings for the Local Leasing site.",
        has_api=True,
        has_docs_path="/docs",
        container_name="scott-localleasing-backend",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Local Leasing Demo",
        url="https://demo.localleasing.markcarpenter1.com",
        category="pete",
        description="Demo environment for Local Leasing — safe to explore",
        what_it_does="A full working copy of Local Leasing loaded with sample data so prospects can explore without affecting real records.",
        container_name="localleasing-demo",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Pete Rental VAPI",
        url="https://pete-rental-vapi.markcarpenter1.com",
        category="pete",
        description="Voice AI for rental property inquiries",
        what_it_does="Answers the phone for rental property inquiries, qualifies tenants, checks availability, and books showings automatically.",
        has_api=True,
        has_docs_path="/docs",
        container_name="pete-rental-vapi",
        docker_networks=["nginx-network"],
        connects_to=["pete-db-api", "vapi2simple-api"],
    ),
    Service(
        name="Pete VAPI Python",
        url="https://invite.markcarpenter1.com",
        category="pete",
        description="Python-powered VAPI integration for Pete real estate calls",
        what_it_does="Handles real-time VAPI voice call logic in Python — looks up property info, qualifies sellers, schedules appointments.",
        has_api=True,
        container_name="pete-vapi-python",
        docker_networks=["nginx-network"],
        connects_to=["pete-db-api", "vapi2simple-api"],
    ),
    Service(
        name="Blog Generator",
        url="https://api.aireinvestor.com",
        category="pete",
        description="AI blog content generator for the AIre Investor brand",
        what_it_does="Automatically writes and publishes real estate blog posts for the AIre Investor site — keeps content fresh without manual effort.",
        has_api=True,
        has_docs_path="/docs",
        container_name="blog-generator",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Scraper API",
        url="https://scraper-api.markcarpenter1.com",
        category="pete",
        description="General-purpose web scraping API",
        what_it_does="Pulls data from websites on demand — property listings, market data, competitor info — and returns it in structured JSON.",
        has_api=True,
        has_docs_path="/docs",
        container_name="scraper-api",
        docker_networks=["nginx-network"],
    ),

    # ─── AI / LLM ─────────────────────────────────────────────────────────────
    Service(
        name="AI Chat (Open WebUI)",
        url="https://ai.markcarpenter1.com",
        category="ai",
        description="Private ChatGPT-style interface running on your own server",
        what_it_does="Talk to local AI models (Mistral, Llama, Codellama) privately — no data to OpenAI, no API costs.",
        container_name="open-webui",
        docker_networks=["nginx-network"],
        connects_to=["ollama"],
    ),
    Service(
        name="Open WebUI (Direct)",
        url="https://open-webui.markcarpenter1.com",
        category="ai",
        description="Direct URL for the Open WebUI chat interface",
        what_it_does="Alternate access point to the private AI chat interface — same service as ai.markcarpenter1.com.",
        container_name="open-webui",
        docker_networks=["nginx-network"],
        connects_to=["ollama"],
    ),
    Service(
        name="Ollama",
        url="https://ollama.markcarpenter1.com",
        category="ai",
        description="Local AI model runner — the engine behind AI Chat",
        what_it_does="Runs open-source AI models directly on server hardware. Your own private ChatGPT engine.",
        has_api=True,
        health_path="/api/tags",
        container_name="ollama",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Fabric",
        url="https://fabric.markcarpenter1.com",
        category="ai",
        description="232+ AI prompt pattern library",
        what_it_does="Pre-built prompt templates for every task: extract key wisdom from articles, summarize YouTube videos, rewrite content.",
        container_name="fabric-dashboard",
        docker_networks=["nginx-network"],
        connects_to=["fabric-service"],
    ),
    Service(
        name="Fabric API",
        url="https://fabric-api.markcarpenter1.com",
        category="ai",
        description="Programmatic access to all Fabric patterns",
        what_it_does="Lets other services and scripts trigger Fabric AI patterns automatically without using the UI.",
        has_api=True,
        has_docs_path="/docs",
        container_name="fabric-service",
        docker_networks=["nginx-network"],
        connects_to=["ollama"],
    ),
    Service(
        name="YT Intel",
        url="https://yt-intel.markcarpenter1.com",
        category="ai",
        description="YouTube Intelligence — extract wisdom from videos",
        what_it_does="Import YouTube watch history, use AI to extract key takeaways from any video. Get 2-hour video insights in minutes.",
        repo="Mark0025/yt-intel",
        has_api=True,
        has_docs_path="/docs",
        container_name="yt-intel",
        docker_networks=["nginx-network"],
        connects_to=["ytintel-db", "youtube-redis"],
    ),
    Service(
        name="YouTube API",
        url="https://youtube-api.markcarpenter1.com",
        category="ai",
        description="YouTube watch history API — stores and serves video history",
        what_it_does="Stores your complete YouTube watch history and serves it to other tools like YT Intel for analysis.",
        has_api=True,
        has_docs_path="/docs",
        container_name="youtube-history-api",
        docker_networks=["nginx-network"],
        connects_to=["ytintel-db", "youtube-redis"],
    ),
    Service(
        name="Unified Knowledge API",
        url="https://unified.markcarpenter1.com",
        category="ai",
        description="Single API giving AI agents a complete picture of the homelab",
        what_it_does="Terry, Claude, or any agent queries this to know what's running, what it does, and how everything connects.",
        has_api=True,
        has_docs_path="/docs",
        container_name="unified-knowledge-api",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Agent EOS",
        url="https://agent-eos.markcarpenter1.com",
        category="ai",
        description="EOS business operating system for AI agent teams",
        what_it_does="Run AI agents like a real company: accountability charts, roles, task assignment — EOS framework for AI.",
        repo="Mark0025/agent-eos",
        container_name="agent-eos",
        docker_networks=["nginx-network"],
        connects_to=["terry-backend"],
    ),
    Service(
        name="NLP Service",
        url="https://nlp-service.markcarpenter1.com",
        category="ai",
        description="Natural Language Processing — entity extraction, sentiment",
        what_it_does="Analyzes text to extract entities (people, places, companies), detect sentiment, understand meaning.",
        has_api=True,
        has_docs_path="/docs",
        container_name="nlp-service",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="WARP Code Analysis",
        url="https://warp-code-analysis-api.markcarpenter1.com",
        category="ai",
        description="Codebase visualizer — maps structure and complexity",
        what_it_does="Analyzes entire repos and generates visual maps of dependencies, complexity hotspots, and improvement candidates.",
        has_api=True,
        has_docs_path="/docs",
        container_name="warp-code-analysis-api",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="MyBookBuddy",
        url="https://mybookbuddyai.com",
        category="ai",
        description="Live public SaaS — AI-powered book tracking",
        what_it_does="Real users can sign up to track books they've read with AI-powered insights and recommendations.",
        repo="Mark0025/my-book-buddy",
        container_name="mybookbuddy-app",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="MyBookBuddy Dev",
        url="https://dev.mybookbuddyai.com",
        category="ai",
        description="Staging environment for MyBookBuddy",
        what_it_does="A safe test copy of MyBookBuddy where new features can be tried without affecting real users.",
        repo="Mark0025/my-book-buddy",
        container_name="mybookbuddy-dev",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Games API",
        url="https://games-api.markcarpenter1.com",
        category="ai",
        description="Backend API for AI-powered games and interactive experiences",
        what_it_does="Powers game logic, leaderboards, and interactive AI features — the engine behind any games built on the homelab.",
        has_api=True,
        has_docs_path="/docs",
        container_name="games-api",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="MCV",
        url="https://mcv.markcarpenter1.com",
        category="ai",
        description="Codebase visualization — interactive maps of repos",
        what_it_does="Generates interactive maps showing how files and modules relate to each other in any codebase.",
        container_name="mcv-mcv-1",
        docker_networks=["nginx-network"],
    ),

    # ─── MONITORING ───────────────────────────────────────────────────────────
    Service(
        name="Homepage Dashboard",
        url="https://dashboard.markcarpenter1.com",
        category="monitoring",
        description="Mission control — tile grid of every running service",
        what_it_does="Visual front page showing every service, its current status, and quick-launch links.",
        container_name="homepage",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Status Page (Uptime Kuma)",
        url="https://status.markcarpenter1.com",
        category="monitoring",
        description="Uptime monitor — checks every URL every few minutes",
        what_it_does="Green/red history showing exactly when each service went down and for how long.",
        container_name="uptime-kuma",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Uptime Kuma (Direct)",
        url="https://uptime-kuma.markcarpenter1.com",
        category="monitoring",
        description="Direct access to Uptime Kuma monitoring dashboard",
        what_it_does="Alternate URL to the uptime monitoring system — same service as status.markcarpenter1.com.",
        container_name="uptime-kuma",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Grafana",
        url="https://grafana.markcarpenter1.com",
        category="monitoring",
        description="Deep metrics dashboards — CPU, memory, network, containers",
        what_it_does="Beautiful charts showing performance over hours, days, weeks. When something feels slow, diagnose it here.",
        container_name="grafana",
        docker_networks=["nginx-network"],
        connects_to=["prometheus"],
    ),
    Service(
        name="Prometheus",
        url="https://prometheus.markcarpenter1.com",
        category="monitoring",
        description="Metrics time-series database powering Grafana",
        what_it_does="Polls every container every 15 seconds, records CPU/requests/errors/etc. Grafana turns those numbers into charts.",
        has_api=True,
        health_path="/-/healthy",
        container_name="prometheus",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Infrastructure Diagram",
        url="https://diagram.markcarpenter1.com",
        category="monitoring",
        description="Live architecture map of the entire homelab",
        what_it_does="Every container, port, public URL, and health status — updates automatically as containers start and stop.",
        has_api=True,
        has_docs_path="/docs",
        container_name="homelab-diagram-server",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="MDOps / Docs",
        url="https://mdops.markcarpenter1.com",
        category="monitoring",
        description="Documentation system with 4,600+ indexed documents",
        what_it_does="AI agents query this to look up how things work — API specs, architecture docs, how-to guides.",
        has_api=True,
        has_docs_path="/docs",
        container_name="mdops",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Working MDOps",
        url="https://working-mdops.markcarpenter1.com",
        category="monitoring",
        description="Stable production build of the MDOps documentation system",
        what_it_does="The tried-and-tested version of MDOps kept running as a fallback while new features are developed on the main instance.",
        has_api=True,
        has_docs_path="/docs",
        container_name="working-mdops",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="NPM Metrics Exporter",
        url="https://metrics.markcarpenter1.com",
        category="monitoring",
        description="Exports Nginx Proxy Manager metrics to Prometheus",
        what_it_does="Converts NPM proxy stats (requests, bandwidth, errors per domain) into Prometheus format so Grafana can chart them.",
        has_api=True,
        container_name="npm-exporter",
        docker_networks=["nginx-network"],
        connects_to=["prometheus"],
    ),
    Service(
        name="Vercel Exporter",
        url="https://vercel.markcarpenter1.com",
        category="monitoring",
        description="Exports Vercel deployment metrics to Prometheus",
        what_it_does="Pulls deployment status, build times, and error rates from Vercel and makes them available in Grafana dashboards.",
        has_api=True,
        container_name="vercel-exporter",
        docker_networks=["nginx-network"],
        connects_to=["prometheus"],
    ),

    # ─── INFRASTRUCTURE ───────────────────────────────────────────────────────
    Service(
        name="Nginx Proxy Manager",
        url="https://nging.markcarpenter1.com",
        category="infrastructure",
        description="Traffic director — front door for every public URL",
        what_it_does="Every request hits NPM first. Handles SSL certs, routes to the right container, controls access.",
        container_name="nginx-proxy-manager",
        docker_networks=["nginx-network", "pete-network"],
    ),
    Service(
        name="NPM Auth Proxy",
        url="https://nging.markcarpenter1.com",
        category="infrastructure",
        description="Authentication layer in front of Nginx Proxy Manager",
        what_it_does="Adds login protection to internal services that don't have their own auth — forces sign-in before reaching sensitive dashboards.",
        container_name="npm-auth-proxy",
        docker_networks=["nginx-network"],
        connects_to=["nginx-proxy-manager"],
    ),
    Service(
        name="Portainer",
        url="https://portainer.markcarpenter1.com",
        category="infrastructure",
        description="Docker management UI — control room for all 90 containers",
        what_it_does="Start, stop, restart containers, view logs, check resource usage — all through a browser.",
        container_name="portainer",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="n8n",
        url="https://n8n.markcarpenter1.com",
        category="infrastructure",
        description="Visual workflow automation — self-hosted Zapier",
        what_it_does="Drag-and-drop automation: 'when a lead comes in → Slack message + CRM entry + schedule call.'",
        container_name="n8n",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Remote Desktop",
        url="https://desktop.markcarpenter1.com",
        category="infrastructure",
        description="Browser-based remote desktop (Apache Guacamole)",
        what_it_does="Access the server's full desktop from any browser anywhere — no VPN, no special software.",
        container_name="guacamole-web",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="MCP Bridge",
        url="https://mcv.markcarpenter1.com",
        category="infrastructure",
        description="Model Context Protocol bridge connecting AI agents to homelab tools",
        what_it_does="Lets Claude and other AI agents call homelab APIs as tools — acts as the translator between AI and your services.",
        has_api=True,
        container_name="mcp-bridge",
        docker_networks=["nginx-network", "pete-network"],
    ),
    Service(
        name="MDDPY MCP",
        url="https://mdops.markcarpenter1.com",
        category="infrastructure",
        description="MCP server exposing the MDOps documentation index to AI agents",
        what_it_does="Wraps the MDOps knowledge base as an AI tool — agents call it to look up docs, specs, and guides during task execution.",
        has_api=True,
        container_name="mddpy-mcp",
        docker_networks=["nginx-network"],
        connects_to=["mdops"],
    ),

    # ─── VOICE / TWILIO ───────────────────────────────────────────────────────
    Service(
        name="Twilio Tools",
        url="https://twilio-tools.markcarpenter1.com",
        category="voice",
        description="Command center for all Twilio phone numbers and call logs",
        what_it_does="Manage phone numbers, view call/SMS history, control voice setup.",
        repo="Mark0025/Twilio_tools",
        container_name="twilio-frontend",
        docker_networks=["nginx-network"],
        connects_to=["twilio-backend"],
    ),
    Service(
        name="Twilio Tools API",
        url="https://twilio-tools-api.markcarpenter1.com",
        category="voice",
        description="Backend — A2P 10DLC compliance, EIN, TrustHub, pipeline tracking",
        what_it_does="Handles US carrier compliance registration for business SMS at scale, EIN verification, and TrustHub profiles.",
        has_api=True,
        has_docs_path="/docs",
        container_name="twilio-backend",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Dev Twilio Tools",
        url="https://dev.twilio-tools.markcarpenter1.com",
        category="voice",
        description="Staging sandbox for Twilio Tools frontend",
        what_it_does="Safe to test changes without risking the live production phone system.",
        container_name="twilio-dev-frontend",
        docker_networks=["nginx-network"],
        connects_to=["twilio-dev-backend"],
    ),
    Service(
        name="Dev Twilio Tools API",
        url="https://dev.twilio-tools-api.markcarpenter1.com",
        category="voice",
        description="Staging backend for Twilio Tools — test compliance logic safely",
        what_it_does="Development version of the Twilio compliance API — test A2P registration and EIN logic without touching live carrier data.",
        has_api=True,
        has_docs_path="/docs",
        container_name="twilio-dev-backend",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="VAPI2Simple UI",
        url="https://vapi2simple-ui.markcarpenter1.com",
        category="voice",
        description="UI to configure VAPI voice AI assistants",
        what_it_does="Simplified setup for AI phone call agents that check Google Calendar and pull CRM data during live calls.",
        repo="Mark0025/VapiSimple2",
        container_name="vapi2simple-ui",
        docker_networks=["nginx-network", "pete-network"],
        connects_to=["vapi2simple-api"],
    ),
    Service(
        name="VAPI2Simple API",
        url="https://vapi2simple-api.markcarpenter1.com",
        category="voice",
        description="Backend for real-time VAPI call lookups",
        what_it_does="During a voice call: checks calendar availability, pulls CRM data, feeds information to the voice AI.",
        has_api=True,
        has_docs_path="/docs",
        container_name="vapi2simple-api",
        docker_networks=["nginx-network", "pete-network"],
        connects_to=["pete-db-api"],
    ),
    Service(
        name="Invite / VAPI Entry",
        url="https://invite.markcarpenter1.com",
        category="voice",
        description="Entry point for VAPI voice AI invitations and onboarding",
        what_it_does="Landing page for incoming VAPI call agent invitations — collects caller info and routes to the right voice AI assistant.",
        container_name="vapi2simple-api",
        docker_networks=["nginx-network", "pete-network"],
        connects_to=["pete-db-api"],
    ),

    # ─── CLIENT / PUBLIC SITES ────────────────────────────────────────────────
    Service(
        name="The AI Real Estate Investor",
        url="https://theairealestateinvestor.com",
        category="sites",
        description="Main brand site for AI real estate investor content",
        what_it_does="Content and education platform for the AI real estate investor brand.",
        container_name="aireinvestor-sites",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="AIre Investor",
        url="https://aireinvestor.com",
        category="sites",
        description="Real estate investor site — blog, resources, lead gen",
        what_it_does="Main AIre Investor brand with blog content, resources, and lead generation.",
        container_name="aireinvestor-sites",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="AIre Investor Next.js",
        url="https://aireinvestor.com",
        category="sites",
        description="Next.js rebuild of the AIre Investor site",
        what_it_does="Modern, fast rebuild of the AIre Investor brand site using Next.js for better performance and SEO.",
        repo="Mark0025/aireinvestor-nextjs",
        container_name="aireinvestor-nextjs",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Fair Deal House Buyer",
        url="https://fairdealhousebuyer.com",
        category="sites",
        description="Primary deal acquisition site — 'we buy houses' lead gen",
        what_it_does="Homeowners in distress fill out a form; leads flow directly into Pete CRM for follow-up.",
        repo="Mark0025/wes",
        container_name="wesapp",
        docker_networks=["nginx-network"],
        connects_to=["wesapp-db"],
    ),
    Service(
        name="Fair Deal Dev",
        url="https://dev.fairdealhousebuyer.com",
        category="sites",
        description="Staging environment for Fair Deal House Buyer",
        what_it_does="Test new features for the Fair Deal lead gen site without affecting the live version that homeowners see.",
        container_name="wesapp-dev",
        docker_networks=["nginx-network"],
        connects_to=["wesapp-db-dev"],
    ),
    Service(
        name="Integrity Buys OKC",
        url="https://integritybuysokc.com",
        category="sites",
        description="Oklahoma City real estate buyer site",
        what_it_does="Lead generation targeting OKC sellers who want a quick sale.",
        container_name="wesapp-pete",
        docker_networks=["nginx-network"],
        connects_to=["wesapp-db-pete"],
    ),
    Service(
        name="Sell Your Oklahoma House",
        url="https://sellyouroklahomahouse.com",
        category="sites",
        description="Lead gen site for Oklahoma homeowners",
        what_it_does="Targets Oklahoma sellers who want to sell quickly — feeds leads into Pete CRM.",
        container_name="aireinvestor-sites",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Hive Market OKC",
        url="https://hivemarketok.com",
        category="sites",
        description="Oklahoma real estate market site",
        what_it_does="Oklahoma-focused real estate market presence and lead generation.",
        container_name="wesapp-dev",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Mark Carpenter Personal Site",
        url="https://autonomous.markcarpenter1.com",
        category="sites",
        description="Mark's personal website — portfolio and homelab showcase",
        what_it_does="Personal site showing projects, homelab architecture, and professional work. Requires auth (Clerk) for protected sections.",
        container_name="markcarpenter1-com-homelab",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Mels Budget",
        url="https://melsbudget.markcarpenter1.com",
        category="sites",
        description="Personal budget tracker — upload CSV, track by category",
        what_it_does="Upload a bank statement export and track spending by category. CSV-only mode, no bank connection needed.",
        container_name="melsbudget",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Mels Budget Dev",
        url="https://dev.melsbudget.markcarpenter1.com",
        category="sites",
        description="Staging environment for Mels Budget app",
        what_it_does="Safe development copy of Mels Budget for testing new features before they go live.",
        container_name="melsbudget-dev",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Remedy",
        url="https://rmd.markcarpenter1.com",
        category="sites",
        description="Remedy web application",
        what_it_does="Web-based remedy and resolution tracking application for managing issues and follow-ups.",
        container_name="remedy-web",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Free Blog (AIre Investor)",
        url="https://aireinvestor.com",
        category="sites",
        description="Auto-generated blog content for AIre Investor",
        what_it_does="AI-written blog posts automatically published to the AIre Investor site — keeps the content calendar full without manual writing.",
        container_name="freeblog-aireinvestor",
        docker_networks=["nginx-network"],
        connects_to=["blog-generator"],
    ),

    # ─── TOOLS / UTILITIES ────────────────────────────────────────────────────
    Service(
        name="HTTPX API",
        url="https://httpx-api.markcarpenter1.com",
        category="tools",
        description="Web probing tool — checks if servers are alive and what they run",
        what_it_does="Tests server responses, detects technology stack. Used for infrastructure auditing and security recon.",
        has_api=True,
        has_docs_path="/docs",
        container_name="httpx-api",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Naabu API",
        url="https://naabu-api.markcarpenter1.com",
        category="tools",
        description="Port scanner — discovers what services are exposed on any server",
        what_it_does="Security audits: 'what is this server actually exposing to the internet?' Discovers open ports and services.",
        has_api=True,
        has_docs_path="/docs",
        container_name="naabu-api",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Scripts Analysis API",
        url="https://scripts-analysis-api.markcarpenter1.com",
        category="tools",
        description="Analyzes shell scripts and automation code across the homelab",
        what_it_does="Catalogs, documents, and analyzes all the shell scripts running on the server — tells you what each script does and when it was last used.",
        has_api=True,
        has_docs_path="/docs",
        container_name="scripts-analysis-api",
        docker_networks=["nginx-network"],
    ),
    Service(
        name="Browser Use",
        url="https://browser-use.markcarpenter1.com",
        category="tools",
        description="AI agent that controls a real web browser",
        what_it_does="Give it a task in plain English; it opens a browser and does it autonomously — form filling, contact finding, web scraping.",
        repo="Mark0025/browser-use",
        has_api=True,
        has_docs_path="/docs",
        container_name="browser-use-api",
        docker_networks=["nginx-network"],
        connects_to=["browser-use-redis", "browser-use-worker"],
    ),
]


CATEGORY_LABELS: dict[str, str] = {
    "terry": "Terry AI Agent",
    "pete": "Pete Real Estate CRM",
    "ai": "AI / LLM Services",
    "monitoring": "Monitoring & Observability",
    "infrastructure": "Infrastructure",
    "voice": "Voice / Twilio",
    "sites": "Public Sites & Lead Gen",
    "tools": "Tools & Utilities",
    "deploy": "Auto-Deploy Webhooks",
}


DOCKER_NETWORKS: dict[str, list[str]] = {
    "nginx-network": [
        "agent-eos",
        "agent-eos-webhook",
        "aireinvestor-nextjs",
        "alertmanager",
        "blog-generator",
        "browser-use-api",
        "browser-use-redis",
        "browser-use-worker",
        "fabric-dashboard",
        "fabric-service",
        "freeblog-aireinvestor",
        "grafana",
        "guacamole-web",
        "homelab-diagram-server",
        "homepage",
        "httpx-api",
        "if3scraper-report",
        "markcarpenter1-com-homelab",
        "mcp-bridge",
        "mddpy-mcp",
        "mdops",
        "melsbudget",
        "melsbudget-dev",
        "my-app-app-1",
        "mybookbuddy-app",
        "mybookbuddy-dev",
        "n8n",
        "naabu-api",
        "nginx-proxy-manager",
        "nlp-service",
        "npm-auth-proxy",
        "npm-auth-webhook",
        "npm-exporter",
        "ollama",
        "open-webui",
        "pete-cleandata",
        "pete-db-api",
        "pete-db-ui",
        "pete-db-webhook",
        "pete-dev-tools-ui",
        "pete-fastapi",
        "pete-image-generator",
        "pete-intercom-app",
        "pete-intercom-webhook",
        "pete-jamie-app",
        "pete-jamie-ui",
        "pete-redis",
        "pete-vapi-python",
        "petevisualizer",
        "petevisualizer-webhook",
        "portainer",
        "prometheus",
        "prometheus-pushgateway",
        "scripts-analysis-api",
        "skip-tracing",
        "skip-tracing-webhook",
        "terry-backend",
        "terry-backend-webhook",
        "terry-conversation",
        "terry-management",
        "terry-management-webhook",
        "terry-memory",
        "terry-performance-api",
        "terry-review-webhook",
        "terry-ui-dev",
        "terry-viewer-next",
        "terry-viewer-next-webhook",
        "twilio-backend",
        "twilio-dev-backend",
        "twilio-dev-frontend",
        "twilio-frontend",
        "twilio-tools-webhook",
        "unified-knowledge-api",
        "uptime-kuma",
        "vapi2simple-api",
        "vapi2simple-ui",
        "vercel-exporter",
        "warp-code-analysis-api",
        "wesapp",
        "wesapp-db",
        "wesapp-db-dev",
        "wesapp-db-pete",
        "wesapp-pete",
        "wesapp-webhook",
        "white-glove-dashboard",
        "working-mdops",
        "youtube-redis",
        "yt-intel",
        "ytintel-db",
    ],
    "pete-network": [
        "if3scraper-report",
        "mcp-bridge",
        "nginx-proxy-manager",
        "pete-cleandata",
        "pete-db-api",
        "pete-db-ui",
        "pete-db-webhook",
        "pete-dev-tools-ui",
        "pete-fastapi",
        "pete-redis",
        "petevisualizer",
        "skip-tracing",
        "skip-tracing-webhook",
        "twilio-backend",
        "twilio-dev-backend",
        "vapi2simple-api",
        "vapi2simple-ui",
    ],
}
